### ISSUE TITLE
Large deobfuscation lags browsers

### ISSUE THREAD

**Issue by Cr3atable** [lelinhtinh/de4js#16]
I have an incredibly large obfuscated block of js that I want to deobfuscate via de4js.
When I try to deobfuscate, the resulting deobfuscated output lags the browser and I am unable to copy said output.
To remedy this I suggest allowing the user to download the resulting deobfuscated js as a file.

**Comment by lelinhtinh** [comment]
Fixed in [v1.6.6](https://github.com/lelinhtinh/de4js/releases/tag/v1.6.6)
