### ISSUE TITLE
Unable to Decode

### ISSUE THREAD

**Issue by Stellarspace** [lelinhtinh/de4js#2]
When there are multiple eval functions within an eval function, the program doesn't decode them.

```javascript
(function () {
    fz__Skm = {};
    fz__Skm.Z_s____u = eval(atob('KGZ1bmN0aW9uKCkgeyByZXR1cm4gIm1hZ2ljX3Nub3dmYWxsXyI7IH0pKCk='));
    fz__Skm.hr_m__Xd = eval(atob('KGZ1bmN0aW9uKCkgeyByZXR1cm4gIlJPQ0siOyB9KSgp'));
    fz__Skm.WES_y_ks = eval(atob('KGZ1bmN0aW9uKCkgeyByZXR1cm4gIl9oaWxpdGVyXyI7IH0pKCk='));
    fz__Skm.VSL____M = eval(atob('KGZ1bmN0aW9uKCkgeyByZXR1cm4gImZ3X3JvdW5kcmFua2luZ19wb2ludHMiOyB9KSgp'));
    fz__Skm.VOjHbyen = eval(atob('KGZ1bmN0aW9uKCkgeyByZXR1cm4gImh0dHA6Ly9kb3dubG9hZC5teXZtay5jb20iOyB9KSgp'));
    fz__Skm._kQXk__x = eval(atob('KGZ1bmN0aW9uKCkgeyByZXR1cm4gIllvdXIgcm9vbSBoYXMgYmVlbiBwdXJjaGFzZWQhIERvIHlvdSB3YW50IHRvIGdvIHRoZXJlIG5vdz8iOyB9KSgp'));
    fz__Skm._LleSZek = eval(atob('KGZ1bmN0aW9uKCkgeyByZXR1cm4gImFkdmVudHVyZWxhbmQiOyB9KSgp'));
    fz__Skm.HR_Rfdln = eval(atob('KGZ1bmN0aW9uKCkgeyByZXR1cm4gImJ1dHRvbi5obWtpY2sucmVkIjsgfSkoKQ=='));
    fz__Skm.p_YUvK_g = eval(atob('KGZ1bmN0aW9uKCkgeyByZXR1cm4gIm1vdmVWIjsgfSkoKQ=='));
    fz__Skm._aBedNmy = eval(atob('KGZ1bmN0aW9uKCkgeyByZXR1cm4gImVtdCI7IH0pKCk='));
    fz__Skm.q_W_j_pQ = eval(atob('KGZ1bmN0aW9uKCkgeyByZXR1cm4gIkZGRTQ4MSI7IH0pKCk='));
    fz__Skm.__Hi_XyE = eval(atob('KGZ1bmN0aW9uKCkgeyByZXR1cm4gImZpbmlzaC5idXR0b24iOyB9KSgp'));
    fz__Skm.LcoEQnzA = eval(atob('KGZ1bmN0aW9uKCkgeyByZXR1cm4gIkVudGVyaW5nOiI7IH0pKCk='));
    fz__Skm.WnwYj_Zr = eval(atob('KGZ1bmN0aW9uKCkgeyByZXR1cm4gIkU4MDMwMyI7IH0pKCk='));
```

**Comment by lelinhtinh** [comment]
Currently, De4js doesn't support this type of obfuscation. Can you send me the full source code?

**Comment by Stellarspace** [comment]
Huh? Yes it does. Ignore the variable change. I am talking about the eval after =. It decodes without the variable and =. It only decodes if the eval is in the first space on the line.

**Comment by lelinhtinh** [comment]
This tool only works with full source code encoding. For multi-part obfuscation, it's difficult to pinpoint which part is obfuscated.

**Comment by Stellarspace** [comment]
@lelinhtinh But when I remove the text before the eval on each line, it is able to decode eval on each line.

**Comment by lelinhtinh** [comment]
That is not the way to solve this encode. If you have the full source code, maybe I will find a way to decode it.

**Comment by Stellarspace** [comment]
@lelinhtinh Here it is: https://raw.githubusercontent.com/Stellarspace/MyVMK/master/client

**Comment by lelinhtinh** [comment]
Variable and function name have been obfuscated, can not be restored.
I wrote decoder tool but source code is too large, it can not work. I split it into several parts to solve and get the results as follows: [MyVMK.js](https://gist.githubusercontent.com/lelinhtinh/a0803015e0ce1fe3ff70d9f840ac7942/raw/300c56748832e0e43c7f3f3d95df10d46a8ba829/MyVMK.js)

**Comment by Stellarspace** [comment]
@lelinhtinh I was trying to tell you that it's obfuscated and can't be restored. I just wanted to decode it.

**Comment by Stellarspace** [comment]
It is missing the code from the top.

**Comment by lelinhtinh** [comment]
I have added the missing libraries:
https://gist.github.com/lelinhtinh/a0803015e0ce1fe3ff70d9f840ac7942
But it still will not work because the data can not be loaded from myvmk.com. This example demonstrates that my decoded code is not missing.

**Comment by Stellarspace** [comment]
@lelinhtinh I'm talking about the code after line 10 is missing. It displays like 300 lines of what I previously posted.
