### ISSUE TITLE
Improvement

### ISSUE THREAD

**Issue by PatSpiegel** [lelinhtinh/de4js#20]
I would like to see deobfuscation of functions
example:
https://cdn.seon.io/v3.0/js/agent.js
https://h.online-metrix.net/fp/check.js?org_id=k8vif92e&session_id=ipaylinks

**Comment by lelinhtinh** [comment]
- **agent.js**: #15 
- **check.js**: I need more similar obfuscation.

**Comment by PatSpiegel** [comment]
> check.js
if you refresh the page, this script will update with the same obfuscation, but with different parameters

**Comment by lelinhtinh** [comment]
Just change the name. Do you know of any other scripts?

**Comment by PatSpiegel** [comment]
> Just change the name. Do you know of any other scripts?

td_3G.tdz_3ca9773a9165473d8acb3384efb8fea2 = new td_3G.td_4q("**DECRYPT_STRING_ALWAYS_CHANGING**");

I met similar scripts (I don’t remember), but there was a similar logic:
1. secret_string
2. decrypter function
3. call decrypt func, like decrypt(from = 3, to = 10), and get "Times New Roms"

**Comment by lelinhtinh** [comment]
I want to understand their rules, so original source code must be different.

**Comment by lelinhtinh** [comment]
Fixed #15, but **agent.js** still hasn't completely decoded.
https://pastebin.com/raw/8KfnfR8X

**Comment by lelinhtinh** [comment]
For backup:
- [agent.txt](https://github.com/lelinhtinh/de4js/files/5071277/agent.txt)
- [check.txt](https://github.com/lelinhtinh/de4js/files/5071278/check.txt)

**Comment by lelinhtinh** [comment]
Resolve **agent.txt** in v1.7.0
