### ISSUE TITLE
Can't enable 'unreadable'

### ISSUE THREAD

**Issue by esseifforte** [lelinhtinh/de4js#28]
hello, I followed the whole installation step by step but I can't make it appear 'unreadable'.
thank you in advance

**Comment by lelinhtinh** [comment]
You need to install UserScript Manager extension, for example: [ViolentMonkey](https://violentmonkey.github.io/).

**Comment by esseifforte** [comment]
@lelinhtinh  thanks for the reply.
Do I install it as a Chrome extension and then? (forgive me, I am not so strong but I have lost my backups and the only one I have is my own js obfuscated by me).
What should I do once installed?

**Comment by esseifforte** [comment]
thanks, I did it. I installed tampermonkey and the helper on OpenUserJS
thank you!
Too bad though that I still see _0x5945 ("0x53").
thank you.

**Comment by lelinhtinh** [comment]
I have no solution, it's a service from [JSNice](http://www.jsnice.org/).
You can use VSCode to [rename symbol](https://code.visualstudio.com/docs/editor/refactoring#_rename-symbol).
Additionally,  this app is having an [unresolved bug](https://github.com/lelinhtinh/de4js/issues/25). You should try the old version [v1.5.2](https://github.com/lelinhtinh/de4js/releases/tag/v1.5.2).
