### ISSUE TITLE
de4js After update does not work as well

### ISSUE THREAD

**Issue by stevenwajones** [lelinhtinh/de4js#46]
yesterday the de4js could decode this snippet, but after the update it can't (I have been using the auto decode button)
`'rarity_longname': {
            'comm': _0x2e2c('0x6d', 'W0Lo'),
            'unco': _0x2e2c('0x6e', 'D7Se'),
            'rare': 'rare',
            'epic': _0x2e2c('0x6f', 'MwDs'),
            'lege': _0x2e2c('0x70', 'p9Oz'),
            'myth': 'mythic'
        },`

**Comment by stevenwajones** [comment]
It also used to convert hexadecimal (0x348294) but It would only be able to do it when set to none and auto decode button

**Comment by stevenwajones** [comment]
this is the script I was decoding [https://tyran.io/script/all.1141.min.js](url)

**Comment by lelinhtinh** [comment]
Temporarily, please uncheck **Evaluate an expression**.

**Comment by lelinhtinh** [comment]
- [all.1141.min.txt](https://github.com/lelinhtinh/de4js/files/5095818/all.1141.min.txt)
- [result.txt](https://github.com/lelinhtinh/de4js/files/5095817/result.txt)
