### ISSUE TITLE
Replacing Array not working with this

### ISSUE THREAD

**Issue by RetiredQQ** [lelinhtinh/de4js#5]
var _0xa5d4 = [
    'particles',
    'flares',
    'Curves'
];

var _0x4a5d = function (_0x3544d8, _0x498512) {
    _0x3544d8 = _0x3544d8 - 0;
    var _0x1ee7ae = _0xa5d4[_0x3544d8];
    return _0x1ee7ae;
};

//console.log(_0x4a5d("0x0"));

Do you support this?

**Comment by lelinhtinh** [comment]
Looks like [JavaScript Obfuscator](https://github.com/javascript-obfuscator/javascript-obfuscator). My tool cannot decode it.
