### ISSUE TITLE
I don't know how I should deobfuscate this javascript

### ISSUE THREAD

**Issue by will2022** [lelinhtinh/de4js#51]
I've been trying to find somehow to deobfuscate this javascript but I don't have a lot of experience with deobfuscating.

Do you have any suggestions?

pastebin.com/KaXTAtE4

**Comment by lelinhtinh** [comment]
For backup: [KaXTAtE4.txt](https://github.com/lelinhtinh/de4js/files/5521321/KaXTAtE4.txt)

Maybe helpful: [a-lot-of-bugs-but-readable.txt](https://github.com/lelinhtinh/de4js/files/5521334/a-lot-of-bugs-but-readable.txt)

**Comment by lelinhtinh** [comment]
Fixed at version 1.10.2 [ahihi.txt](https://github.com/lelinhtinh/de4js/files/5542372/ahihi.txt)
