### ISSUE TITLE
Not working... It always say "Please wait....."

### ISSUE THREAD

**Issue by Vilakk** [lelinhtinh/de4js#61]
😢

**Comment by sugappa** [comment]
ye me too

**Comment by trailyy** [comment]
same for me, when using obfuscator.io to be exact

**Comment by doko-desuka** [comment]
You can see the error if you open your dev tools (F12 key on most desktop browsers), then go to the Console tab.

**Comment by fapkamaster** [comment]
If you tried installing Userscript to access "Unreadable", you should try to disable it.
