### ISSUE TITLE
javascript-objuscator can not be deobfuscated

### ISSUE THREAD

**Issue by SplotyCode** [lelinhtinh/de4js#9]
The javascript-objuscator can not be deobfuscated. I tried it with diffrent files even the example file from javascript-objuscator can not be deobfuscator.

**Comment by lelinhtinh** [comment]
You're right, this application doesn't deobfuscate [JavaScript-obfuscator](https://obfuscator.io/), but it works with [Javascript Obfuscator](https://javascriptobfuscator.com/Javascript-Obfuscator.aspx).
Same #5
